server:
  port: 7899
spring:
  redis:
    port: 7011
    host: 39.104.50.29
    timeout: 2000
    jedis:
      pool:
        max-active: 6 #最大连接数
        max-idle: 6 #最大空闲数
        min-idle: 2 #最小空闲数

